config/routes.rb
Rails.application.routes.draw do
  resources :tasks, except: :show

  root 'tasks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id         :bigint           not null, primary key
#  body       :text
#  name       :string           not null
#  status     :string           default("ongoing"), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Task < ApplicationRecord
  extend Enumerize

  # constants
  STATUSES = %i[ongoing completed canceled].freeze

  # validations
  validates :name, presence: true
  validates :status, presence: true

  # attributes
  enumerize :status, in: STATUSES
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :prepare_task, only: %i[show edit update destroy]

  def index
    @tasks = Task.all.order(status: :desc)
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      @task.broadcast_prepend_to 'tasks-channel', target: 'task-collection', partial: 'tasks/task'
      redirect_to tasks_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @task.update(task_params)
      redirect_to tasks_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @task.destroy!

    redirect_to tasks_path
  end

  private

  def prepare_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(
      :name,
      :status,
      :body
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-28 mt-28 px-5 flex flex-col gap-8">
      <%= yield %>
    </main>
  </body>
</html>

app/views/tasks/_form.html.slim
= simple_form_for task do |f|
  .grid.gap-2.grid-cols-3
    = f.input :name,
              label: false,
              input_html: { class: 'w-full' },
              wrapper_html: { class: 'col-span-2' },
              placeholder: 'Task name (required)'

    = f.input :status,
              label: false,
              input_html: { class: 'w-full' },
              include_blank: false

    = f.input :body,
              label: false,
              input_html: { class: 'w-full' },
              wrapper_html: { class: 'col-span-3' },
              placeholder: 'Task description'

  .flex.gap-4.mt-2
    = f.submit 'Add', class: 'px-8 py-2 bg-blue-500 hover:bg-blue-700 text-white rounded-lg'
    = link_to 'Cancel', tasks_path, class: 'bg-gray-200 px-8 py-2 rounded-lg'

app/views/tasks/_task.html.slim
= turbo_frame_tag "edit-task-#{task.id}"
  .flex.flex-col.gap-2
    .flex.items-center.justify-between
      .text-xl.font-bold
        = [task.name, task.status_text].join(" - ")
      .flex.items-center.gap-4
        = link_to 'Edit', edit_task_path(task), class: 'bg-gray-200 px-8 py-2 rounded-lg'
        = button_to 'Destroy', task_path(task), method: :delete, data: { turbo_confirm: 'This action is irreversible, are you sure?', turbo_frame: '_top' }, class: 'bg-red-500 text-white px-6 py-2 rounded-lg'

    p.w-full.border.border-gray-300.rounded-lg.p-4
      - if task.body.blank?
        = '<insert your task description here>'
      - else
        = task.body

app/views/tasks/edit.html.slim
= turbo_frame_tag "edit-task-#{@task.id}" do
  = render 'form', task: @task

app/views/tasks/index.html.slim
= turbo_stream_from 'tasks-channel'

.flex.items-center.justify-between
  h1.text-3xl.font-bold
    | To-do list

  = link_to 'New task', new_task_path, data: { turbo_frame: 'new-task' }, class: 'bg-blue-500 text-white rounded-lg px-8 py-2 hover:bg-blue-700'

= turbo_frame_tag 'new-task'

#task-collection.flex.flex-col.gap-4
  = render @tasks

app/views/tasks/new.html.slim
= turbo_frame_tag 'new-task' do
  = render 'form', task: @task